void exception_handler(int ex)
{
	kprint("An exception has occured.", 12);
	while(1);
}
